# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wozpcJZ6p_uOFc_fVcRu2FqqRDJdgcMK

# Proyek Klasifikasi Gambar: Flower Image Classification
- **Nama:** `Shendi Teuku Maulana Efendi`
- **Email:** `shendyteuku2@gmail.com`
- **ID Dicoding:** `shendyeff`

## Import Semua Packages/Library yang Digunakan
"""

!pip uninstall tensorflowjs
!pip install tensorflowjs

import os
import random
import shutil
import pathlib
import glob
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm
from PIL import Image
import cv2
import gdown
import absl.logging
import logging

warnings.filterwarnings('ignore')

import tensorflow as tf
import tensorflowjs as tfjs
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import (
    Conv2D, MaxPooling2D, Flatten, Dropout, Dense,
    GlobalAveragePooling2D, BatchNormalization
)

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetV2B0, MobileNetV2
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.mobilenet_v3 import preprocess_input

print(f'TensorFlow version: {tf.__version__}')

print(f'TensorFlow.js version: {tfjs.__version__}')

"""## Data Preparation

`Link Dataset!` <br>
[![Google Drive Dataset](https://img.shields.io/badge/Download%20Dataset-Google%20Drive-blue?style=for-the-badge&logo=google-drive)](https://drive.google.com/file/d/1m9UBYCzLElZ8x_-b_jysE7A9y-jSq04u/view?usp=drive_link)

### Data Loading
"""

file_id = '1m9UBYCzLElZ8x_-b_jysE7A9y-jSq04u'

url = f'https://drive.google.com/uc?id={file_id}'
output = '/content/dataset-flowers.zip'

gdown.download(url, output, quiet=False)

"""#### Unzip Dataset"""

!unzip dataset-flowers.zip -d dataset-flowers/

remove_file = '/content/dataset-flowers.zip'
os.remove(remove_file)

"""#### Cek Keberagaman Resolusi Dataset"""

def count_images_and_resolution(base_path, target_resolution=None):
    # Dictionary untuk menyimpan jumlah gambar per kelas
    class_count = {}

    # Dictionary untuk menyimpan jumlah gambar per resolusi
    resolution_count = {}

    for root, dirs, files in os.walk(base_path):
        # Mengabaikan folder root yang tidak memiliki gambar
        if root == base_path:
            continue
        class_name = os.path.basename(root)
        class_count[class_name] = len(files)

        for file in files:
            file_path = os.path.join(root, file)
            # Check if the file is an image file
            if not file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                continue # Skip if not an image file
            with Image.open(file_path) as img:
                width, height = img.size
                resolution = f"{width}x{height}"
                if resolution not in resolution_count:
                    resolution_count[resolution] = 0
                resolution_count[resolution] += 1

                # Menghitung jumlah gambar dengan resolusi target_resolution
                if target_resolution and resolution == target_resolution:
                    if 'target' not in resolution_count:
                        resolution_count['target'] = 0
                    resolution_count['target'] += 1

    return class_count, resolution_count

base_path = "/content/dataset-flowers"
target_resolution = "256x256"

class_count, resolution_count = count_images_and_resolution(base_path, target_resolution)

print("Jumlah gambar per kelas:")
for class_name, count in class_count.items():
    print(f"{class_name}: {count}")

print("\nJumlah gambar per resolusi:")
for resolution, count in resolution_count.items():
    print(f"{resolution}: {count}")

"""#### Mengecek Daftar Label Kelas
Untuk sekarang dataset masih terbagi menjadi `train` dan `val`, dimana nanti dilakukan penyesuaian dataset pada tahap splitting yaitu menjadi `train`, `valid`, dan `test`
"""

image_data='/content/dataset-flowers/train'
pd.DataFrame(os.listdir(image_data),columns=['Files_Name'])

image_test_data='/content/dataset-flowers/val'
pd.DataFrame(os.listdir(image_test_data),columns=['Files_Name'])

files = [i for i in glob.glob(image_data + "//*//*")]
np.random.shuffle(files)
labels = [os.path.dirname(i).split("/")[-1] for i in files]
data = zip(files, labels)
dataframe = pd.DataFrame(data, columns = ["Image", "Label"])
dataframe

sns.countplot(x = dataframe["Label"])
plt.xticks(rotation = 90);

"""### Data Preprocessing

#### Split Dataset
"""

# Path asal
base_dir = 'dataset-flowers'
combined_dir = 'combined_dataset'

# Gabungkan semua gambar dari train dan val ke satu folder sementara
if not os.path.exists(combined_dir):
    os.makedirs(combined_dir)

    for folder in ['train', 'val']:
        folder_path = os.path.join(base_dir, folder)
        for class_name in os.listdir(folder_path):
            class_path = os.path.join(folder_path, class_name)

            # ⛔ Skip kalau bukan folder
            if not os.path.isdir(class_path):
                continue

            dest_class_path = os.path.join(combined_dir, class_name)
            os.makedirs(dest_class_path, exist_ok=True)

            for img_file in os.listdir(class_path):
                src = os.path.join(class_path, img_file)
                dst = os.path.join(dest_class_path, img_file)
                shutil.copy2(src, dst)

# Bikin folder baru buat split ulang
split_base = 'dataset_split'
for split in ['train', 'val', 'test']:
    for class_name in os.listdir(combined_dir):
        os.makedirs(os.path.join(split_base, split, class_name), exist_ok=True)

# Parameter split
train_ratio = 0.7
val_ratio = 0.15
test_ratio = 0.15

# Split dan salin file
for class_name in os.listdir(combined_dir):
    class_dir = os.path.join(combined_dir, class_name)

    if not os.path.isdir(class_dir):
        continue

    images = os.listdir(class_dir)
    random.shuffle(images)

    total = len(images)
    train_end = int(train_ratio * total)
    val_end = train_end + int(val_ratio * total)

    train_imgs = images[:train_end]
    val_imgs = images[train_end:val_end]
    test_imgs = images[val_end:]

    for img in train_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(split_base, 'train', class_name, img))
    for img in val_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(split_base, 'val', class_name, img))
    for img in test_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(split_base, 'test', class_name, img))

print("Dataset successfully re-split into train, val, and test.")

"""#### Load Train, Validation, dan Test Set dari Folder Split"""

base_dir = 'dataset_split'
batch_size = 32
target_size = (224, 224)

# Load train dataset
train_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    directory=os.path.join(base_dir, 'train'),
    label_mode='categorical',  # pakai categorical kalau multi-class
    image_size=target_size,
    batch_size=batch_size,
    shuffle=True,
    seed=123
)

# Load validation dataset
val_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    directory=os.path.join(base_dir, 'val'),
    label_mode='categorical',
    image_size=target_size,
    batch_size=batch_size,
    shuffle=False,
    seed=123
)

# Load test dataset
test_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    directory=os.path.join(base_dir, 'test'),
    label_mode='categorical',
    image_size=target_size,
    batch_size=batch_size,
    shuffle=False,
    seed=123
)

class_names = train_dataset.class_names
class_names

plt.figure(figsize=(15, 20))
for images, labels in train_dataset.take(1):
    for i in range(8):
        ax = plt.subplot(8, 4, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))

        predicted_class_index = np.argmax(labels[i].numpy())

        plt.title(class_names[predicted_class_index])
        plt.axis("off")

"""## Modelling"""

base_model = tf.keras.applications.MobileNetV3Large(input_shape=(224,224,3), include_top=False, weights='imagenet')
base_model.trainable = False

keras_model = tf.keras.models.Sequential()

# Add Input layer
keras_model.add(tf.keras.Input(shape=(224,224,3)))

# Add base model (MobileNetV3Large)
keras_model.add(base_model)

# Add custom layers: Conv2D and MaxPooling2D
keras_model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='relu',padding='same'))  # 64 filters, 3x3 kernel, add padding
keras_model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))         # Max Pooling with 2x2 pool size

keras_model.add(tf.keras.layers.Conv2D(128, (3, 3), activation='relu',padding='same')) # 128 filters, 3x3 kernel, add padding
keras_model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))         # Max Pooling with 2x2 pool size

# Flatten and add Dense layers
keras_model.add(tf.keras.layers.Flatten())
keras_model.add(tf.keras.layers.Dropout(0.5))
keras_model.add(tf.keras.layers.Dense(14, activation=tf.nn.softmax))

# Print model summary
keras_model.summary()

tf.keras.utils.plot_model(keras_model, to_file='model.png', show_shapes=True, show_layer_names=True,show_dtype=True,dpi=80)

"""### Implementasi Callback"""

checkpoint = ModelCheckpoint("my_keras_model.keras", save_best_only=True)
early_stopping = EarlyStopping(patience=5, restore_best_weights=True)

keras_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

"""### Train Model"""

hist = keras_model.fit(
    train_dataset,
    epochs=40,
    validation_data=val_dataset,  # pakai val_dataset, bukan validation dari split
    callbacks=[checkpoint, early_stopping]
)

hist_=pd.DataFrame(hist.history)
hist_

hist_['accuracy'].plot(kind='line', figsize=(8, 4), title='accuracy')
plt.gca().spines[['top', 'right']].set_visible(False)

"""## Evaluasi dan Visualisasi"""

score, acc = keras_model.evaluate(val_dataset)
print('Test Loss =', score)
print('Test Accuracy =', acc)

plt.figure(figsize=(15,5))
plt.subplot(1,2,1)
plt.plot(hist_['loss'],label='Train_Loss')
plt.plot(hist_['val_loss'],label='Validation_Loss')
plt.title('Train_Loss & Validation_Loss',fontsize=20)
plt.legend()
plt.subplot(1,2,2)
plt.plot(hist_['accuracy'],label='Train_Accuracy')
plt.plot(hist_['val_accuracy'],label='Validation_Accuracy')
plt.title('Train_Accuracy & Validation_Accuracy',fontsize=20)
plt.legend()

"""## Konversi Model

Konversi model menjadi format `saved_model`
"""

keras_model.export("saved_model/my_model")

"""Konversi model menjadi format `TF Lite`"""

# 1. Konversi SavedModel ke TFLite
converter = tf.lite.TFLiteConverter.from_saved_model("saved_model/my_model")
tflite_model = converter.convert()

# 2. Buat folder simpan model TFLite
os.makedirs('tflite', exist_ok=True)

# 3. Simpan model .tflite
with open('tflite/model.tflite', 'wb') as f:
    f.write(tflite_model)

print("Model berhasil dikonversi ke TFLite dan disimpan sebagai 'tflite/model.tflite'")

# 4. Simpan file label (klasifikasi 14 jenis bunga)
class_names = [
    'astilbe', 'bellflower', 'black_eyed_susan', 'calendula', 'california_poppy',
    'carnation', 'common_daisy', 'coreopsis', 'dandelion', 'iris',
    'rose', 'sunflower', 'tulip', 'water_lily'
]

with open('tflite/label.txt', 'w') as f:
    for name in class_names:
        f.write(name + '\n')

print("Label berhasil disimpan sebagai 'tflite/label.txt'")

"""Konversi model menjadi format `TFJS`"""

!tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    saved_model/my_model \
    tfjs_model

"""Menyimpan dependencies yang digunakan pada project"""

!pip freeze > requirements.txt

"""## Inference (Optional)"""

# Load the TFLite model using tf.lite.Interpreter
interpreter = tf.lite.Interpreter(model_path='tflite/model.tflite')
interpreter.allocate_tensors()

# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Path gambar yang di-upload
img_path = "/content/dataset_split/test/black_eyed_susan/1057222299_1389a4723e_c.jpg"  # Nama file yang di-upload

# Load dan preprocess gambar yang di-upload
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)

# Set input tensor and invoke the interpreter
interpreter.set_tensor(input_details[0]['index'], img_array)
interpreter.invoke()

# Get the output tensor
predictions = interpreter.get_tensor(output_details[0]['index'])

# Get predicted class
predicted_class = np.argmax(predictions, axis=1)

predicted_label = class_names[predicted_class[0]]

# Display the image and prediction
plt.imshow(img)
plt.title(f'Predicted: {predicted_label}')
plt.axis('off')
plt.show()

# Load the TFLite model using tf.lite.Interpreter
interpreter = tf.lite.Interpreter(model_path='tflite/model.tflite')
interpreter.allocate_tensors()

# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Path gambar yang di-upload
img_path = "/content/dataset_split/test/tulip/10400415455_7a4796d598_c.jpg"  # Nama file yang di-upload

# Load dan preprocess gambar yang di-upload
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)

# Set input tensor and invoke the interpreter
interpreter.set_tensor(input_details[0]['index'], img_array)
interpreter.invoke()

# Get the output tensor
predictions = interpreter.get_tensor(output_details[0]['index'])

# Get predicted class
predicted_class = np.argmax(predictions, axis=1)

predicted_label = class_names[predicted_class[0]]

# Display the image and prediction
plt.imshow(img)
plt.title(f'Predicted: {predicted_label}')
plt.axis('off')
plt.show()

# Load the TFLite model using tf.lite.Interpreter
interpreter = tf.lite.Interpreter(model_path='tflite/model.tflite')
interpreter.allocate_tensors()

# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Path gambar yang di-upload
img_path = "/content/dataset_split/test/dandelion/10774849493_bb82957f1b_c.jpg"  # Nama file yang di-upload

# Load dan preprocess gambar yang di-upload
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)

# Set input tensor and invoke the interpreter
interpreter.set_tensor(input_details[0]['index'], img_array)
interpreter.invoke()

# Get the output tensor
predictions = interpreter.get_tensor(output_details[0]['index'])

# Get predicted class
predicted_class = np.argmax(predictions, axis=1)

predicted_label = class_names[predicted_class[0]]

# Display the image and prediction
plt.imshow(img)
plt.title(f'Predicted: {predicted_label}')
plt.axis('off')
plt.show()

# Load the TFLite model using tf.lite.Interpreter
interpreter = tf.lite.Interpreter(model_path='tflite/model.tflite')
interpreter.allocate_tensors()

# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Path gambar yang di-upload
img_path = "/content/dataset_split/test/iris/164507281_f5c9796e11_c.jpg"  # Nama file yang di-upload

# Load dan preprocess gambar yang di-upload
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)

# Set input tensor and invoke the interpreter
interpreter.set_tensor(input_details[0]['index'], img_array)
interpreter.invoke()

# Get the output tensor
predictions = interpreter.get_tensor(output_details[0]['index'])

# Get predicted class
predicted_class = np.argmax(predictions, axis=1)

predicted_label = class_names[predicted_class[0]]

# Display the image and prediction
plt.imshow(img)
plt.title(f'Predicted: {predicted_label}')
plt.axis('off')
plt.show()